# Generated by Django 4.2.10 on 2026-06-01 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='service',
            new_name='services_status_352bca_idx',
            old_name='services_status_featured_idx',
        ),
        migrations.RenameIndex(
            model_name='service',
            new_name='services_categor_e16510_idx',
            old_name='services_category_status_idx',
        ),
    ]
