# Generated by Django 4.2.10 on 2026-06-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('service', models.CharField(choices=[('ai_ml', 'AI & Machine Learning'), ('financial', 'Financial Systems'), ('cloud', 'Cloud & DevOps'), ('web_mobile', 'Web & Mobile'), ('cybersecurity', 'Cybersecurity'), ('other', 'Other')], default='other', max_length=20)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('budget', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('spam', 'Spam')], db_index=True, default='new', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
            ],
            options={
                'db_table': 'contacts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='contacts_status_241cac_idx')],
            },
        ),
    ]
