# Generated by Django 4.2.10 on 2026-06-01 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aigeneratedcontent',
            new_name='ai_generate_content_f05bc3_idx',
            old_name='ai_gen_type_date_idx',
        ),
        migrations.RenameIndex(
            model_name='aigeneratedcontent',
            new_name='ai_generate_created_36abca_idx',
            old_name='ai_gen_user_date_idx',
        ),
        migrations.RenameIndex(
            model_name='aiusagelog',
            new_name='ai_usage_lo_feature_ccd6e0_idx',
            old_name='ai_usage_feature_date_idx',
        ),
        migrations.AlterField(
            model_name='aigeneratedcontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='aisession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
