# Generated by Django 4.2.10 on 2026-06-01 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
