# Generated by Django 4.2.10 on 2026-06-01 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contentreview',
            name='unique_content_review',
        ),
        migrations.RenameIndex(
            model_name='contentreview',
            new_name='workflow_co_status_02ff66_idx',
            old_name='workflow_cr_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='workflownotification',
            new_name='workflow_no_user_id_4914dc_idx',
            old_name='workflow_notif_user_read_idx',
        ),
        migrations.AlterUniqueTogether(
            name='contentreview',
            unique_together={('content_type', 'object_id')},
        ),
    ]
